# 🎬 TMDB Movie Insights — EDA

Este notebook realiza el **Análisis Exploratorio de Datos (EDA)** del dataset TMDB. El objetivo es entender la estructura de los datos, detectar problemas de calidad y **documentar las decisiones** que luego se implementan en el pipeline (`src/`).

## 1. Carga de datos

In [6]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

df = pd.read_csv('../data/raw/tmdb_2020_to_2025.csv')
df.head()

,Unnamed: 0,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,0,False,/hpXBJxLD2SEf8l2CspmSeiHrBKX.jpg,"[18, 27, 14]",1062722,en,Frankenstein,"Dr. Victor Frankenstein, a brilliant but egoti...",951.3460,/g4JtvGlQO7DByTI6frUobqvSL3R.jpg,2025-10-17,Frankenstein,False,7.907,1075
1,1,False,/d6HIjhk2f8BiZnVQ43gUv67khmX.jpg,"[10749, 18]",1231813,ko,자매의 스와핑,Sisters Ji-soo and Ji-yeong decided to sell th...,14.2714,/lqjkmFmV62JEUGKK7E1UwX7PDDT.jpg,2023-12-19,Sister Swapping,False,6.600,14
2,2,False,/82lM4GJ9uuNvNDOEpxFy77uv4Ak.jpg,"[28, 878, 12]",1242898,en,Predator: Badlands,"Cast out from his clan, a young Predator finds...",314.6851,/pHpq9yNUIo6aDoCXEBzjSolywgz.jpg,2025-11-05,Predator: Badlands,False,7.200,266
3,3,False,/6zKjoOOb3OZnZuiHtQZn4Kd69Gq.jpg,"[27, 53]",1197137,en,Black Phone 2,"Four years after escaping The Grabber, Finney ...",242.3412,/xUWUODKPIilQoFUzjHM6wKJkP3Y.jpg,2025-10-15,Black Phone 2,False,7.186,437
4,4,False,/vZK3f5N8Fv2LcyFYLwt6dz0HE1H.jpg,"[28, 35]",1161617,en,Code 3,A burned-out paramedic tries to survive his la...,251.8624,/gIAYMDb5mIAeCAj76q1sRsKjkzo.jpg,2025-09-12,Code 3,False,7.075,87

## 2. Inspección general

In [7]:
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         9999 non-null   int64
 1   adult              9999 non-null   bool
 2   backdrop_path      8118 non-null   object
 3   genre_ids          9999 non-null   object
 4   id                 9999 non-null   int64
 5   original_language  9999 non-null   object
 6   original_title     9999 non-null   object
 7   overview           9721 non-null   object
 8   popularity         9999 non-null   float64
 9   poster_path        9756 non-null   object
 10  release_date       9999 non-null   object
 11  title              9999 non-null   object
 12  video              9999 non-null   bool
 13  vote_average       9999 non-null   float64
 14  vote_count         9999 non-null   int64
dtypes: bool(2), float64(2), int64(3), object(8)
memory usage: 1.0+ MB

,Unnamed: 0,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
count,9999.000000,9999,8118,9999,9.999000e+03,9999,9999,9721,9999.000000,9756,9999,9999,9999,9999.000000,9999.000000
unique,NaN,1,8110,1520,NaN,81,9817,9699,NaN,9742,2009,9712,1,NaN,NaN
top,NaN,False,/2SF1K5gdfELr08uoWoY3ASYwJR0.jpg,[18],NaN,en,The Stranger,An Eternalism film.,NaN,/lkVABE2fwJD3bobpl8P1l6BxJM6.jpg,2021-01-01,The Stranger,False,NaN,NaN
freq,NaN,9999,5,1328,NaN,5566,6,15,NaN,10,34,6,9999,NaN,NaN
mean,4999.000000,NaN,NaN,NaN,9.797428e+05,NaN,NaN,NaN,5.814750,NaN,NaN,NaN,NaN,4.551764,221.900790
std,2886.607005,NaN,NaN,NaN,2.630966e+05,NaN,NaN,NaN,13.101449,NaN,NaN,NaN,NaN,2.968713,879.465244
min,0.000000,NaN,NaN,NaN,5.492000e+03,NaN,NaN,NaN,0.192900,NaN,NaN,NaN,NaN,0.000000,0.000000
25%,2499.500000,NaN,NaN,NaN,7.845155e+05,NaN,NaN,NaN,3.673650,NaN,NaN,NaN,NaN,0.000000,0.000000
50%,4999.000000,NaN,NaN,NaN,9.500850e+05,NaN,NaN,NaN,4.320600,NaN,NaN,NaN,NaN,5.708000,6.000000
75%,7498.500000,NaN,NaN,NaN,1.175968e+06,NaN,NaN,NaN,5.650550,NaN,NaN,NaN,NaN,6.724000,61.000000
max,9998.000000,NaN,NaN,NaN,1.576287e+06,NaN,NaN,NaN,951.346000,NaN,NaN,NaN,NaN,10.000000,21265.000000

## 3. Valores nulos

In [8]:
df.isna().mean().sort_values(ascending=False)

backdrop_path        0.188119
overview             0.027803
poster_path          0.024302
genre_ids            0.000000
id                   0.000000
Unnamed: 0           0.000000
adult                0.000000
original_title       0.000000
original_language    0.000000
popularity           0.000000
release_date         0.000000
title                0.000000
video                0.000000
vote_average         0.000000
vote_count           0.000000
dtype: float64

## 4. Manejo de fechas

In [9]:
df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')
df['release_year'] = df['release_date'].dt.year
df[['release_date','release_year']].head()

  release_date  release_year
0   2025-10-17          2025
1   2023-12-19          2023
2   2025-11-05          2025
3   2025-10-15          2025
4   2025-09-12          2025

## 7. Data Set limpio
### Carga del Dataset limpio

In [13]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path

pd.set_option('display.max_columns', None)

# Ruta robusta (recomendada)
BASE_DIR = Path.cwd().parent
DATA_PATH = BASE_DIR / "data" / "processed" / "tmdb_movies_clean.csv"

dflimpio = pd.read_csv(DATA_PATH)
df.head()

,Unnamed: 0,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,0,False,/hpXBJxLD2SEf8l2CspmSeiHrBKX.jpg,"[18, 27, 14]",1062722,en,Frankenstein,"Dr. Victor Frankenstein, a brilliant but egoti...",951.3460,/g4JtvGlQO7DByTI6frUobqvSL3R.jpg,2025-10-17,Frankenstein,False,7.907,1075
1,1,False,/d6HIjhk2f8BiZnVQ43gUv67khmX.jpg,"[10749, 18]",1231813,ko,자매의 스와핑,Sisters Ji-soo and Ji-yeong decided to sell th...,14.2714,/lqjkmFmV62JEUGKK7E1UwX7PDDT.jpg,2023-12-19,Sister Swapping,False,6.600,14
2,2,False,/82lM4GJ9uuNvNDOEpxFy77uv4Ak.jpg,"[28, 878, 12]",1242898,en,Predator: Badlands,"Cast out from his clan, a young Predator finds...",314.6851,/pHpq9yNUIo6aDoCXEBzjSolywgz.jpg,2025-11-05,Predator: Badlands,False,7.200,266
3,3,False,/6zKjoOOb3OZnZuiHtQZn4Kd69Gq.jpg,"[27, 53]",1197137,en,Black Phone 2,"Four years after escaping The Grabber, Finney ...",242.3412,/xUWUODKPIilQoFUzjHM6wKJkP3Y.jpg,2025-10-15,Black Phone 2,False,7.186,437
4,4,False,/vZK3f5N8Fv2LcyFYLwt6dz0HE1H.jpg,"[28, 35]",1161617,en,Code 3,A burned-out paramedic tries to survive his la...,251.8624,/gIAYMDb5mIAeCAj76q1sRsKjkzo.jpg,2025-09-12,Code 3,False,7.075,87

## 8. Inspección general del dataset

In [14]:
dflimpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         9999 non-null   int64
 1   adult              9999 non-null   bool
 2   backdrop_path      8118 non-null   object
 3   genre_ids          9999 non-null   object
 4   id                 9999 non-null   int64
 5   original_language  9999 non-null   object
 6   original_title     9999 non-null   object
 7   overview           9721 non-null   object
 8   popularity         9999 non-null   float64
 9   poster_path        9756 non-null   object
 10  release_date       9999 non-null   object
 11  title              9999 non-null   object
 12  video              9999 non-null   bool
 13  vote_average       9999 non-null   float64
 14  vote_count         9999 non-null   int64
dtypes: bool(2), float64(2), int64(3), object(8)
memory usage: 1.0+ MB

## Media, mediana, moda, varianza, desviación estándar, mínimos y máximos

In [16]:

stats = dflimpio.describe().T
stats

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,9999.0,4999.000000,2886.607005,0.0000,2499.50000,4999.0000,7.498500e+03,9998.000
id,9999.0,979742.833183,263096.572337,5492.0000,784515.50000,950085.0000,1.175968e+06,1576287.000
popularity,9999.0,5.814750,13.101449,0.1929,3.67365,4.3206,5.650550e+00,951.346
vote_average,9999.0,4.551764,2.968713,0.0000,0.00000,5.7080,6.724000e+00,10.000
vote_count,9999.0,221.900790,879.465244,0.0000,0.00000,6.0000,6.100000e+01,21265.000

## Moda

In [17]:
dflimpio.mode().iloc[0]

Unnamed: 0                                          0
adult                                           False
backdrop_path        /2SF1K5gdfELr08uoWoY3ASYwJR0.jpg
genre_ids                                        [18]
id                                               5492
original_language                                  en
original_title                           The Stranger
overview                          An Eternalism film.
popularity                                     4.0023
poster_path          /lkVABE2fwJD3bobpl8P1l6BxJM6.jpg
release_date                               2021-01-01
title                                    The Stranger
video                                           False
vote_average                                      0.0
vote_count                                        0.0
Name: 0, dtype: object

## Varianza

In [19]:
dflimpio.var(numeric_only=True)

Unnamed: 0      8.332500e+06
adult           0.000000e+00
id              6.921981e+10
popularity      1.716480e+02
video           0.000000e+00
vote_average    8.813258e+00
vote_count      7.734591e+05
dtype: float64

### Análisis de valores nulos (post-limpieza)

In [20]:
dflimpio.isna().sum()

Unnamed: 0              0
adult                   0
backdrop_path        1881
genre_ids               0
id                      0
original_language       0
original_title          0
overview              278
popularity              0
poster_path           243
release_date            0
title                   0
video                   0
vote_average            0
vote_count              0
dtype: int64

In [22]:
dflimpio.isna().mean() * 100

Unnamed: 0            0.000000
adult                 0.000000
backdrop_path        18.811881
genre_ids             0.000000
id                    0.000000
original_language     0.000000
original_title        0.000000
overview              2.780278
popularity            0.000000
poster_path           2.430243
release_date          0.000000
title                 0.000000
video                 0.000000
vote_average          0.000000
vote_count            0.000000
dtype: float64